name: kyudo_record
description: A new Flutter project.
version: 1.0.0+2

publish_to: "none"

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  get: ^4.6.5
  flutter_heat_map: ^1.2.1
  isar: ^2.5.0
  isar_flutter_libs: ^2.5.0
  path_provider: ^2.0.9
  isar_generator: ^2.5.0
  build_runner: ^2.1.10
  font_awesome_flutter: ^10.1.0
  flutter_slidable: ^1.3.0
  toggle_switch: ^2.0.1
  lottie: ^1.3.0
  table_calendar: ^3.0.6
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
  fonts:
    - family: NotoSansHK
      fonts:
        - asset: assets/fonts/NotoSansHK-Regular.otf
