name: kyudo_record
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  get: ^4.6.1
  flutter_heat_map: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: NotoSansHK
      fonts:
        - asset: assets/fonts/NotoSansHK-Regular.otf
